I have already installed numpy. Let's go ahead and import it.

In [1]:
import numpy as np

In [2]:
rank_1_array = np.array([1, 2, 3])
rank_1_array

array([1, 2, 3])

In [3]:
rank_2_array = np.array([[1, 2, 3], [4, 5, 6]])
rank_2_array

array([[1, 2, 3],
       [4, 5, 6]])

## Accessing Array Elements

Can access elements in an array through a somewhat familiar syntax. Note the syntax for the multidimensional case:

In [4]:
print(rank_1_array[0], rank_1_array[1], rank_1_array[2])

1 2 3


In [5]:
print(rank_2_array[0, 0], rank_2_array[1, 2])

1 6


Rank means the number of dimensions in an array. Shape is a tuple that gives the size of each dimension.

In [6]:
print(rank_1_array.shape)
print(rank_2_array.shape)

(3,)
(2, 3)


Numpy has utility methods for creating certain types of arrays:
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#routines-array-creation

In [7]:
all_zeros = np.zeros((4, 9))
all_zeros  # Contains floats by default

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## Slicing Arrays

You can slice arrays. Be careful though! Slices in numpy still reference the original value. Any changes in a slice will carry over to the original array.

In [10]:
original = np.identity(4)
print("original:", original, sep="\n")

example_slice = original[1:3, 2:]
print("example:", example_slice, sep="\n")
print()

example_slice[0, 1] = 99
print("updated example:", example_slice, sep="\n")
print("updated original:", original, sep="\n")

original:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
example:
[[0. 0.]
 [1. 0.]]

updated example:
[[ 0. 99.]
 [ 1.  0.]]
updated original:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0. 99.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


Using integers instead of slices is also possible

In [11]:
original = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("original:", original, sep="\n")

integer_slice = original[0:2, 3]
print("integer_slice:", integer_slice, sep="\n")

column_slice = original[0:2, 3:]
print("column_slice:", column_slice, sep="\n")

original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
integer_slice:
[4 8]
column_slice:
[[4]
 [8]]


Numpy can evaluate boolean conditions for you and create a boolean index.

In [12]:
original = np.array([[1, 2, 3], [5, 8, 9]])
print("original:", original, sep="\n")

boolean_index = (original %2 == 0)
print("boolean:", boolean_index, sep="\n")

other_array = np.array([[10, 20, 30], [40, 50, 60]])
print("other_array:", other_array, sep="\n")

print("boolean index with other array:",
      other_array[boolean_index],
      sep="\n")

original:
[[1 2 3]
 [5 8 9]]
boolean:
[[False  True False]
 [False  True False]]
other_array:
[[10 20 30]
 [40 50 60]]
boolean index with other array:
[20 50]


Full details about slicing can be found in the documentation: https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

## Data types

Data types (dtype) in numpy are quite a bit different than types in Python. A dtype will describe exactly how a particular value is stored in memory.
https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

For now, just know that dtype can be used to specify the type of data you want to store in an array. By default, we get float64, but we can specify something else.

In [13]:
float_array = np.identity(2)
print(float_array)
print(type(float_array[0, 0]))
print()

# Store 32 bit integers instead
int_array = np.identity(2, dtype=np.int32)
print(int_array)
print(type(int_array[0, 0]))
print()

[[1. 0.]
 [0. 1.]]
<class 'numpy.float64'>

[[1 0]
 [0 1]]
<class 'numpy.int32'>



For now, don't worry about big-endian vs little-endian. Just know that it is possible to specify if you ever have to.
https://en.wikipedia.org/wiki/Endianness

## Array Math

Can do basic math either with functions or with operators.

In [14]:
identity = np.identity(3)
other_array = np.full((3, 3), 5)

print(other_array + identity, end="\n\n")
print(other_array - identity, end="\n\n")
print(other_array * identity, end="\n\n")
print(identity / other_array, end="\n\n")

[[6. 5. 5.]
 [5. 6. 5.]
 [5. 5. 6.]]

[[4. 5. 5.]
 [5. 4. 5.]
 [5. 5. 4.]]

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]

[[0.2 0.  0. ]
 [0.  0.2 0. ]
 [0.  0.  0.2]]



In [15]:
print(np.add(other_array, identity), end="\n\n")
print(np.subtract(other_array, identity), end="\n\n")
print(np.multiply(other_array, identity), end="\n\n")
print(np.divide(identity, other_array), end="\n\n")

[[6. 5. 5.]
 [5. 6. 5.]
 [5. 5. 6.]]

[[4. 5. 5.]
 [5. 4. 5.]
 [5. 5. 4.]]

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]

[[0.2 0.  0. ]
 [0.  0.2 0. ]
 [0.  0.  0.2]]



If you need to perform inner products, use np.dot().

In [16]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([[4], [5], [6]])
array_3 = np.array([10])

print(np.dot(array_1, array_2))
print(np.dot(array_2, array_3))

[32]
[40 50 60]


A matrix can be transposed with the T operator.

In [17]:
print(array_2)
print(array_2.T)

[[4]
 [5]
 [6]]
[[4 5 6]]


In [18]:
np.dot(array_2, array_2.T)

array([[16, 20, 24],
       [20, 25, 30],
       [24, 30, 36]])

## Broadcasting

You can operate on arrays of different sizes, subject to numpy's broadcasting rules. See the documentation for an explanation. https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

In [19]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
